---
- name: Mount backup drive
  mount:
    path: "{{ backup_drive_mount_point }}"
    src: UUID={{ backup_drive_uuid }}
    fstype: "{{ backup_drive_fstype }}"
    state: mounted

- name: Install Samba
  include_role:
    name: bertvv.samba
  vars:
    samba_netbios_name: raspberrypi1
    samba_server_string: '%h server (Samba, Ubuntu)'
    samba_workgroup: SIEMHOME

    samba_global_include: global-include.conf
    samba_homes_include: homes-include.conf
    
    samba_log: /var/log/samba/log.%m
    samba_log_size: 1000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '

    samba_map_to_guest: bad user
    samba_users:
      - name: michael
        password: Qfun.919

    samba_load_homes: true

    samba_shares:
      - name: Backup
        comment: 'Backup Folder'
        path: /mnt/backup
        read only: 'yes'
        browseable: 'yes'
      - name: sambashare
        comment: 'Samba on Ubuntu'
        path: /home/michael/sambashare
        read only: 'no'
        browseable: 'yes'

- name: Allow Samba throuhg firewall
  ufw:
    rule: allow
    name: Samba

