name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up correct configuration files
        run: "sed -i 's/user: michael/user: runner/g' vars/user_environment.yml"

      - name: Bootstrap the environment
        run: sudo sh bootstrap.sh
        
      - name: Attempt to provision the box
        run: ansible-playbook -K playbook.yaml
